[package]
name = "wfly-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
notify = { version = "8.1.0", features = ["serde"] }
nix = { version = "0.30", features = ["process"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1", features = ["full"] }
libc = "0.2"


